AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda function that moves data from AWS IoT Core to AWS Dynamo DB

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 60

Resources:
  IoTCoreToDynamoDbFunctionForVectarCleanEnergy:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IoTCoreToDynamoDbForVectarCleanEnergy
      CodeUri: .
      Handler: app.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VectarCleanEnergy
      Events:
        IoTCoreToDynamoDbForVectarCleanEnergy:
          Type: IoTRule
          Properties:
            Sql: "SELECT * FROM 'ecoWise/0001/pub'"
            AwsIotSqlVersion: "2016-03-23"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "aws-sdk"

  VectarCleanEnergy:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "DeviceId"
          AttributeType: "S"
        - AttributeName: "Timestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "DeviceId"
          KeyType: "HASH"
        - AttributeName: "Timestamp"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
