AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple AWS Lambda function that moves data from AWS IoT Core to AWS Dynamo DB

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 60
    Layers:
      - arn:aws:lambda:eu-north-1:580510132728:layer:GeohashingLayer:7

Resources:
  IoTCoreToDynamoDbFunctionForEfotainer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IoTCoreToDynamoDbForEfotainer
      CodeUri: .
      Handler: app.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Efotainer
      Events:
        IoTCoreToDynamoDbForEfotainer:
          Type: IoTRule
          Properties:
            Sql: "SELECT * FROM 'efotainer/pub'"
            AwsIotSqlVersion: "2016-03-23"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "aws-sdk"
          - "geohashing"

  Efotainer:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Name"
          AttributeType: "S"
        - AttributeName: "Timestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "Name"
          KeyType: "HASH"
        - AttributeName: "Timestamp"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
